<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-AGDRQC9" failures="3" tests="5" name="chrome" time="110.441" errors="0" timestamp="2023-10-31T19:11:03 GMT">
  <testcase classname="testCases.TC_003_Login_DataDriven" name="test_TestDriven" time="13.985"/>
  <testcase classname="testCases.TC_003_Login_DataDriven" name="test_TestDriven" time="4.383">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC_003_Login_DataDriven.test_TestDriven(TC_003_Login_DataDriven.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_TestDriven -->
  <testcase classname="testCases.TC_003_Login_DataDriven" name="test_TestDriven" time="24.079">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC_003_Login_DataDriven.test_TestDriven(TC_003_Login_DataDriven.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_TestDriven -->
  <testcase classname="testCases.TC_003_Login_DataDriven" name="test_TestDriven" time="29.628">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003_Login_DataDriven.test_TestDriven(TC_003_Login_DataDriven.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test_TestDriven -->
  <testcase classname="testCases.TC_003_Login_DataDriven" name="test_TestDriven" time="14.041"/>
</testsuite> <!-- chrome -->
