<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-AGDRQC9" failures="3" tests="3" name="screfix(failed)" time="119.729" errors="0" timestamp="2023-11-01T20:13:21 GMT">
  <testcase classname="testCases.TC_003_Login_DataDriven" name="test_TestDriven" time="34.857">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003_Login_DataDriven.test_TestDriven(TC_003_Login_DataDriven.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test_TestDriven -->
  <testcase classname="testCases.TC_003_Login_DataDriven" name="test_TestDriven" time="35.699">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003_Login_DataDriven.test_TestDriven(TC_003_Login_DataDriven.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test_TestDriven -->
  <testcase classname="testCases.TC_003_Login_DataDriven" name="test_TestDriven" time="33.421">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003_Login_DataDriven.test_TestDriven(TC_003_Login_DataDriven.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test_TestDriven -->
</testsuite> <!-- screfix(failed) -->
